# Generated by Django 4.0.3 on 2022-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
