# Generated by Django 4.0.3 on 2022-03-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_comunnes_comunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.comunas'),
            preserve_default=False,
        ),
    ]
