# Generated by Django 4.0.3 on 2022-03-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
            preserve_default=False,
        ),
    ]
