# Generated by Django 4.0.3 on 2022-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
