# Generated by Django 4.0.3 on 2022-03-16 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_regions_tipo_usuario_alter_user_numero_comunnes'),
    ]

    operations = [
        migrations.CreateModel(
            name='productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios_asociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productor')),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recolector')),
            ],
        ),
        migrations.CreateModel(
            name='residuos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilos', models.IntegerField()),
                ('usuarios_asociados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios_asociados')),
            ],
        ),
    ]
