# Generated by Django 4.0.3 on 2022-03-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productor_recolector_usuarios_asociados_residuos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios_asociados',
            new_name='asociados',
        ),
    ]
