# Generated by Django 4.0.3 on 2022-03-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_usuarios_asociados_asociados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productor', to='app.productor'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='recolector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolector', to='app.recolector'),
        ),
    ]
