# Generated by Django 4.0.3 on 2022-03-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_asociados_productor_alter_asociados_recolector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='recolector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hola', to='app.recolector'),
        ),
    ]
