# Generated by Django 4.0.3 on 2022-03-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_asociados_recolector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productor'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='recolector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recolector'),
        ),
    ]
