# Generated by Django 4.0.3 on 2022-03-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_asociados_productor_alter_asociados_recolector'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comunnes',
            new_name='comunas',
        ),
    ]
